### ISSUE TITLE
doc for using vscode on cubic

### ISSUE THREAD

**Issue by zhao-cy** [PennLINC/PennLINC.github.io#17]

**Comment by zhao-cy** [comment]
showed to informatics team this morning (1/31); However we realized that it's very tricky to use vscode on cubic - it's easy to create/run files with personal user account (instead of project user), and will leave issues of file permissions...

ON HOLD now:
Currently just a secret trick within informatics team; after figuring out how to ssh directly as project user, will create such doc for the lab

**Comment by TinasheMTapera** [comment]
1. install nvm first: https://github.com/nvm-sh/nvm#installing-and-updating

install with:
```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
```

check with `nvm -v`

--------------------

2. use nvm 14 to get node 14

```
nvm install --lts # install base node
nvm install 14    # set 14
```

check with `node -v`

-------------------

3. use node to install code-server

```
npm install -g code-server --unsafe-perm
```

-------------------

4. pull docker image

```
cd singularity-images && singularity pull docker://codercom/code-server
```

-------------------

5. start singularity as a service for persistence

```
cd ~ && singularity instance start PATH_TO_SIF YOUR_NAME
```
--------------------

6. start code server

```
singularity exec instance://YOUR_NAME code-server --port PORT &
```

to make sure you get the cbica tempdir (necessary for `/scratch`), instead start it as

```
singularity instance start --bind $PWD,$TMPDIR PATH NAME
```

and

```
singularity exec --bind $PWD,$TMPDIR instance://NAME code-server --port PORT &
```

**Comment by zhao-cy** [comment]
So far two comments:

add some explanation why we do not recommend to directly use local vscode to access cubic projects (i.e. may create files under personal user account)
if facing the error when installing nvm:
bash: line xxx: /cbica/projects/ProjectName/.bashrc: Permission denied
try:
$ cd ~
$ chmod +w .bashrc

**Comment by zhao-cy** [comment]
Now I'm at step 3 `npm install -g code-server --unsafe-perm`. However there were some errors:

## If I follow the instructions and use node 14: `nvm install 14`, it will throw out these errors:

> npm WARN notsup Unsupported engine for code-server@4.4.0: wanted: {"node":"16"} (current: {"node":"14.19.2","npm":"6.14.17"})
npm WARN notsup Not compatible with your version of node/npm: code-server@4.4.0

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.28.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the argon2@0.28.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /cbica/projects/fixel_db/.npm/_logs/2022-05-14T22_17_18_985Z-debug.log

## Because above error message wanted node version 16, I switched to 16 then. But there were still errors:

$ nvm install 16
v16.15.0 is already installed.
Now using node v16.15.0 (npm v8.5.5)
$ node -v
v16.15.0

$ npm install -g code-server --unsafe-perm
npm notice 
npm notice New minor version of npm available! 8.5.5 -> 8.10.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.10.0
npm notice Run npm install -g npm@8.10.0 to update!
npm notice 
npm ERR! code 1
npm ERR! path /gpfs/fs001/cbica/projects/fixel_db/.nvm/versions/node/v16.15.0/lib/node_modules/code-server/node_modules/argon2
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.15.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.6.8 found at "/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.15.0/node-v16.15.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.15.0/node-v16.15.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v16.15.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.15.0/SHASUMS256.txt
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/gpfs/fs001/cbica/projects/fixel_db/.nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/gpfs/fs001/cbica/projects/fixel_db/.nvm/versions/node/v16.15.0/lib/node_modules/code-server/node_modules/argon2/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/gpfs/fs001/cbica/projects/fixel_db/.nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/cbica/projects/fixel_db/.cache/node-gyp/16.15.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/cbica/projects/fixel_db/.cache/node-gyp/16.15.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/gpfs/fs001/cbica/projects/fixel_db/.nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/cbica/projects/fixel_db/.cache/node-gyp/16.15.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/gpfs/fs001/cbica/projects/fixel_db/.nvm/versions/node/v16.15.0/lib/node_modules/code-server/node_modules/argon2',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! node:internal/modules/cjs/loader:936
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module 'node-addon-api'
npm ERR! Require stack:
npm ERR! - /gpfs/fs001/cbica/projects/fixel_db/.nvm/versions/node/v16.15.0/lib/node_modules/code-server/node_modules/argon2/[eval]
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)
npm ERR!     at [eval]:1:1
npm ERR!     at Script.runInThisContext (node:vm:129:12)
npm ERR!     at Object.runInThisContext (node:vm:305:38)
npm ERR!     at node:internal/process/execution:76:19
npm ERR!     at [eval]-wrapper:6:22
npm ERR!     at evalScript (node:internal/process/execution:75:60) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/gpfs/fs001/cbica/projects/fixel_db/.nvm/versions/node/v16.15.0/lib/node_modules/code-server/node_modules/argon2/[eval]'
npm ERR!   ]
npm ERR! }
npm ERR! gyp: Call to 'node -p "require('node-addon-api').include"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/gpfs/fs001/cbica/projects/fixel_db/.nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 3.10.0-1062.el7.x86_64
npm ERR! gyp ERR! command "/gpfs/fs001/cbica/projects/fixel_db/.nvm/versions/node/v16.15.0/bin/node" "/gpfs/fs001/cbica/projects/fixel_db/.nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /gpfs/fs001/cbica/projects/fixel_db/.nvm/versions/node/v16.15.0/lib/node_modules/code-server/node_modules/argon2
npm ERR! gyp ERR! node -v v16.15.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /cbica/projects/fixel_db/.npm/_logs/2022-05-14T22_21_07_616Z-debug-0.log

## Other details:
I have logged in as a project user

**Comment by TinasheMTapera** [comment]
have you tried installing `gyp` before hand?
```
npm install -g node-gyp
npm install -g node-pre-gyp
```

**Comment by zhao-cy** [comment]
Hmmm, I just tried install `gyp`, but the errors persist... (for both node version 14+ and 16+, same errors).
I also tried `conda activate` beforehand but still failed...
I'm on cubic's `fixel_db` in case you wanted to check there.
Thanks!

**Comment by TinasheMTapera** [comment]
@zhao-cy could you try
```
npm install -g yarn
yarn install code-server
```
Or something to that effect. I think installing code-server with `yarn` worked for me recently

**Comment by zhao-cy** [comment]
^^ works, except that it's not `yarn install`, but should be `yarn add code-server` (probably some updates in yarn)
checking the remaining steps now...
